### ISSUE TITLE
What is everybody going to be working on?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-code-sprint-2021-07#1]
Post a comment letting us know what you are going to be working on.

**Comment by doublebyte1** [comment]
I will try to test some server and client implementations of OGC API records:

[Pygeoapi](https://pygeoapi.io/)
[Geonetwork](https://geonetwork-opensource.org/)
[QGIS Metasearch](https://docs.qgis.org/testing/en/docs/user_manual/plugins/core_plugins/plugins_metasearch.html?highlight=metasearch)

**Comment by aaime** [comment]
Work on a first implementation of OGC API - Coverages in GeoServer.

**Comment by jerstlouis** [comment]
We will be improving our implementation of _OGC API - Processes_ and _Coverages_ in GNOSIS Map Server and Cartographer (client), including interaction of the two via the _Workflows_ extension.
In particular we will be working on a server-side coverage processor, and improve support for multiple bands.

We hope to perform Technology Integration Experiments with our client & server against other implementations of _Processes_, _Coverages_ and _Workflows_. We are also planning to work on improving the _Workflows_ [specification](https://docs.ogc.org/DRAFTS/21-009.html), re-organizing it in separate conformance classes and updating it to reflect the finalization of _OGC API - Processes - Part 1: Core_.

We will also be working on improving the _Coverages_ specifications.

Another topic of interest is discussing a _Coverages_ extension allowing to combine discovery/_OGC API - Records_ (e.g. to discover scenes with a maximum cloud cover using scene metadata) and/or value-based filtering (e.g. using a cloud coverage band) with data access (e.g. _Coverage_ request), using CQL for example. This would be a very useful capability for a GeoDataCube API (related: https://github.com/opengeospatial/ogcapi-coverages/issues/103 & https://github.com/opengeospatial/ogcapi-coverages/issues/105).

**Comment by tomkralidis** [comment]
On my side, as part of various [Geopython](https://geopython.github.io) projects as time permits:

- OGC API - Records: help test/move forward specification and clarify relationship with STAC
- OGC API - Processes: update [pygeoapi](https://pygeoapi.io) per the latest changes/updates to the specification
- OGC API - Coverages: help with YAML schemas

IMO clarifying the OARec and STAC relationship and any resulting changes to the OARec specification are critical path.  cc @pvretano @cholmes

**Comment by EHJ-52n** [comment]
I will work on pygeoapi and try to implement a processes api server for an open data cube instance.

* [x] Identify potential processes to implement: [Spectral Products: Vegetation, Water, Urbanization](https://nbviewer.jupyter.org/github/crc-si/odc-sandbox-notebooks/blob/master/dcal/DCAL_Spectral_Products.ipynb)
* [x] add dummy process to current tb17 test deployment
* [ ] <s>implement one of above identified processes</s>

**Comment by pvgenuchten** [comment]
i'm wrapping up https://github.com/geopython/pygeoapi/pull/725 related to multilingual support (of special interest to ogc-api-records)
i hope to work on qgis metasearch (ogc-api-records client)
Linking to WMS/WFS from a ogc-api-records record, to facilitate instant binding

**Comment by ByronCinNZ** [comment]
Keen to work on any OGCAPIR issues involving ISO19115 or DCAT.
Also, OpenSearch - ATOM support. Willing to create a simple client to test.
Do have a problem with time zones here in New Zealand. So will mostly be available either early or late.

**Comment by gardengeek99** [comment]
Server and client implementations of OGC API - Processes

**Comment by ghobona** [comment]
I'll be documenting an '[OGC API - Processes Getting Started guide for Spring.io Developers](https://github.com/opengeospatial/ogcapi-code-sprint-2021-07/tree/main/Draft_Spring_Guide_for_OGC_API_Proceses)'. 

The idea is to take new implementers through the stages of using  Spring with openapitools-generator on OGC API - Processes. Note that the guide will use a 'profile' of the building blocks.

**Comment by ghobona** [comment]
On Day 2 and 3, I will set up a maven and TestNG project for the Executable Test Suite (ETS) of OGC API - Coverages.

**Comment by pvretano** [comment]
I would welcome one or more people working on an ISO19115 extensions since there seems to be a lot of interest in it.  I think it would involve mapping the core record model into ISO19115 (which should be fairly easy) and then describing the additional elements of the ISO19115 model.  @tomkralidis @kalxas worked on something so ping them for sure.

Put the work in the "proposals" directory for now.  There is already a proposal for faceted searches there so you can use that as a template if you like.

**Comment by jerstlouis** [comment]
@pvretano we should also consider how this ISO19115 extension fits in with _Common_, e.g. https://github.com/opengeospatial/ogcapi-common/issues/69#issuecomment-864623592  (point 4).

Collections becomes searchable with ISO 19115 fields, and ISO19115 metadata can be retrieved following a `data-meta` relation link (from either collection or dataset).

**Comment by ByronCinNZ** [comment]
@pvretano I can do the mappings of ISO115 to core easy enough. Not clear what clear what describing the additional elements involves.  Keen to see  @tomkralidis @kalxas  previous work

**Comment by pvretano** [comment]
@ByronCinNZ it is basically a documentation exercise.

- **STEP 1**: Map as many ISO 19115 fields as you can to the core record properties (see [Table 13 & Table 14](https://docs.ogc.org/DRAFTS/20-004.html#query-response))
- **STEP 2**: Decide which properties from ISO19115, not already mapped in STEP 1, you want to add to the record schema to enhance its information content; it can be all of them or some subset -- whatever your community needs.
- **STEP 3**: Decide which record encoding(s) you want to support ... for the sake of example lets say you decide GeoJSON.
- **STEP 4**: OGC API Records already maps the core record properties to GeoJSON [here](https://docs.ogc.org/DRAFTS/20-004.html#requirements-class-json-clause).
- **STEP 5**: Decide how you want the add the properties you identified in STEP 2 into a GeoJSON record/feature.  This can be by adding them to the "properties" section or as top level "foreign elements" as the GeoJSON specification calls them.  As long as you don't disturb the mapping from STEP 4 you are free to add them any way you like.  STAC, for example, adds a top-level "assets" object to the GeoJSON record.

There are some other housekeeping steps you need to describe such as how you negotiate to the format(s) you decided to support in STEP 3.  This basically means describing which MIME types or profile tokens that should be used.

And that, in broad strokes, is pretty much it...  

Makes sense?

If yes, then I should probably document this process somehow in the specification.

**Comment by ByronCinNZ** [comment]
@pvretano Yes that makes sense. I can easily commit to completing step 1 today. Hopefully will get a start on step 2 through 5 in an iterative manner.

I have been doing a great deal of work with the ICSM Metadata Working Group (ANZLIC) which provides official guidance for spatial metadata across Australia and New Zealand. This I can use for guidance for additional required fields.

I would note that I will be using ISO 19115-1:2018 and not the older versions. This may be slightly at odds with @tomkralidis @kalxas previous work

**Comment by francbartoli** [comment]
On my side: touching [pygeoapi](https://github.com/geopython/pygeoapi) for starting an early implementation for the OAProc workflows extension

**Comment by NazihFino** [comment]
On behalf of Ethar Inc & Open AR Cloud, [Philip Lamb](https://github.com/philip-lamb), [Colin Steinmann](https://github.com/metaColin), [Nazih Fino](https://github.com/NazihFino) worked to extend our web-based geospatial visualization tool to render datasets from the coverages API. Additionally, because of our participation in Testbed 17, we are especially focused on visualizing datasets that contain a time dimension, and or orientation data. We believe datasets that contain these dimensions are especially well suited to Geo Data Cubes
