### ISSUE TITLE
How to support propagation of Exceptions up a workflow

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-code-sprint-2021-07#18]
The proposed Workflows extension of OGC API - Processes needs to include support for propagation of errors up a service chain.

For example, in a 10 step workflow, if an error occurs at step 5, the process at step 5 needs to be able to notify the processes at step 1, 2, 3 and 4 that an error occurred (e.g. in case a roll back is needed).

Some of the research questions will include:

* How should the Exception class be modelled (i.e. profiling of the Exception class from OGC API - Common)?
* How will the process at step 5 notify the processes up the chain and also the client that triggered the workflow?

**Comment by jerstlouis** [comment]
At each level of the workflow, the request to either setup/validate the workflow (or more rarely, data access requests) may return an error. If an error is returned, that service will in turn return an error to the service acting as a client (or the final client) that invoked it. That error may carry along with any additional information, the error information from the nested service (it should probably be a recommendation, but not a requirement).

Those exceptions should probably be based on the [exception schema](https://github.com/opengeospatial/ogcapi-common/blob/master/core/openapi/schemas/exception.yaml) defined by Common.

The nice thing with first setting up the workflow chain without yet initiating the processing is that the end user client can quickly get feedback about the correctness of the workflow, and once the workflow is registered across the chain the actual data retrieval requests triggering processing should go very smoothly.

It is also the intent that this pre-registration of the workflows could minimize the latency along workflows involving several nodes, as the nodes could leverage some intelligence to pre-empt requests based on current request trends (especially at a large scale when multiple clients are involved), and perform hybrid on-demand / batch processing by prioritizing immediate needs, while using the most recent available data.

**Comment by ghobona** [comment]
How does the service that had the error notify the the service acting as a client that invoked it?

Perhaps each service in the workflow should offer a process for receiving error notifications (with job number as one of the inputs).

Alternatively, we leave it to the implementer to decide how they build the error reporting. Some might decide to use OGC PubSub, others might decide to use AsyncAPI, whereas others might decide to ignore error reporting altogether. All being reasonable solutions depending on the use case of the workflow.

**Comment by jerstlouis** [comment]
> How does the service that had the error notify the the service acting as a client that invoked it?

When doing the workflow setup/validation (i.e. _collection_ or _landingPage_ response mode), each service in the chain, just like the client itself, is doing a POST of the execution request. So the error is simply the return code for that POST to `/processes/{processId}/execution?response=collection`.

When doing data access request that triggers processing for an AoI, each request along the nodes is simply a typical OGC API data request, e.g. a GetCoverage at `/coverage`. So again the error is simply the usual error conditions of e.g. the Coverages API (HTTP code response to GET `/coverage`).

When doing sync or async processing as per Processes - Core, again the requests are the usual Processes core request and the usual error condition applies. (either from the POST to `/processes/{processId}/execution` for sync, or from the job status inside the document retrieved by GET `/jobs/{jobId}` for async).

There is no need to define anything new for this, it's already built into those constituent OGC API specifications.

The whole idea of _Workflows_ is to leverage existing building blocks -- it's just defining an interface to connect data access building blocks with processing building blocks (at either end).

**Comment by ghobona** [comment]
@jerstlouis Ok, understood. Thanks.
