### ISSUE TITLE
Clause 2 and 7.3.3.2 in OGC API - Coverages are inconsistent

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-code-sprint-2021-07#20]
Clause 2 suggests that there is a Core conformance class.

Clause 7.3.3.2 calls the conformance class geodata-coverage (http://www.opengis.net/spec/ogcapi-coverages-1/1.0/conf/geodata-coverage)

These two clauses need to be reconciled.

**Comment by jerstlouis** [comment]
Done in https://github.com/opengeospatial/ogcapi-coverages/commit/2af589845cf3e060181cb2e4f60ae0597bafc354

**Comment by ghobona** [comment]
That's great! Thanks.
